# Generated by Django 6.1.1 on 2026-09-17 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=64)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('device_category', models.CharField(blank=True, max_length=20)),
                ('browser_category', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['date', 'visitor_id'], name='analytics_p_date_d7d8df_idx'), models.Index(fields=['date', 'path'], name='analytics_p_date_8f5558_idx')],
            },
        ),
    ]
