# Generated by Django 6.1.1 on 2026-09-17 05:02
#
# Data migration for the News -> Research rename. The old `apps.news` app has
# been removed from INSTALLED_APPS (its models/views/urls/dashboard entries
# were replaced by apps.research), but its tables and rows are intentionally
# left untouched in the database — nothing here drops or mutates them. This
# migration only *copies* any existing news_newscategory / news_newsarticle
# rows into the new research_* tables (preserving primary keys, so existing
# foreign keys such as article.author_id keep working), so no production
# content is lost by the rename. It is written against raw table names via
# the DB cursor (not the old Django models) because apps.news no longer
# exists as an installed app for this migration to import models from.
from django.db import migrations


def copy_legacy_news_data(apps, schema_editor):
    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())
    if "news_newscategory" not in existing_tables or "news_newsarticle" not in existing_tables:
        return

    with connection.cursor() as cursor:
        cursor.execute(
            'SELECT id, created_at, updated_at, "order", active, name, slug FROM news_newscategory'
        )
        columns = [col[0] for col in cursor.description]
        categories = [dict(zip(columns, row)) for row in cursor.fetchall()]

        for row in categories:
            cursor.execute(
                'INSERT INTO research_researchcategory '
                '(id, created_at, updated_at, "order", active, name, slug) '
                "VALUES (%s, %s, %s, %s, %s, %s, %s)",
                [row["id"], row["created_at"], row["updated_at"], row["order"], row["active"], row["name"], row["slug"]],
            )

        cursor.execute(
            "SELECT id, created_at, updated_at, meta_title, meta_description, title, slug, excerpt, "
            "content, featured_image, featured, published, published_at, author_id, category_id "
            "FROM news_newsarticle"
        )
        columns = [col[0] for col in cursor.description]
        articles = [dict(zip(columns, row)) for row in cursor.fetchall()]

        for row in articles:
            cursor.execute(
                "INSERT INTO research_researcharticle "
                "(id, created_at, updated_at, meta_title, meta_description, title, slug, excerpt, "
                "content, featured_image, featured, published, published_at, author_id, category_id) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
                [
                    row["id"], row["created_at"], row["updated_at"], row["meta_title"], row["meta_description"],
                    row["title"], row["slug"], row["excerpt"], row["content"], row["featured_image"],
                    row["featured"], row["published"], row["published_at"], row["author_id"], row["category_id"],
                ],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_legacy_news_data, migrations.RunPython.noop),
    ]
