# Generated by Django 6.0.5 on 2026-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_migrate_legacy_news_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcharticle',
            name='content_fa',
            field=models.TextField(blank=True, verbose_name='content (Dari)'),
        ),
        migrations.AddField(
            model_name='researcharticle',
            name='content_ps',
            field=models.TextField(blank=True, verbose_name='content (Pashto)'),
        ),
        migrations.AddField(
            model_name='researcharticle',
            name='excerpt_fa',
            field=models.CharField(blank=True, max_length=300, verbose_name='excerpt (Dari)'),
        ),
        migrations.AddField(
            model_name='researcharticle',
            name='excerpt_ps',
            field=models.CharField(blank=True, max_length=300, verbose_name='excerpt (Pashto)'),
        ),
        migrations.AddField(
            model_name='researcharticle',
            name='title_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='title (Dari)'),
        ),
        migrations.AddField(
            model_name='researcharticle',
            name='title_ps',
            field=models.CharField(blank=True, max_length=200, verbose_name='title (Pashto)'),
        ),
        migrations.AddField(
            model_name='researchcategory',
            name='name_fa',
            field=models.CharField(blank=True, max_length=120, verbose_name='name (Dari)'),
        ),
        migrations.AddField(
            model_name='researchcategory',
            name='name_ps',
            field=models.CharField(blank=True, max_length=120, verbose_name='name (Pashto)'),
        ),
    ]
