# Generated by Django 6.0.5 on 2026-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='description (Dari)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ps',
            field=models.TextField(blank=True, verbose_name='description (Pashto)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_fa',
            field=models.CharField(blank=True, max_length=120, verbose_name='name (Dari)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ps',
            field=models.CharField(blank=True, max_length=120, verbose_name='name (Pashto)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_fa',
            field=models.CharField(blank=True, max_length=255, verbose_name='short description (Dari)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ps',
            field=models.CharField(blank=True, max_length=255, verbose_name='short description (Pashto)'),
        ),
    ]
