# Generated by Django 6.1.1 on 2026-09-11 08:48

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='company/', validators=[apps.core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', validators=[apps.core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', validators=[apps.core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to='hero_slides/', validators=[apps.core.validators.validate_file_size]),
        ),
    ]
