# Generated by Django 6.0.5 on 2026-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_companyinfo_favicon_alter_companyinfo_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='address_fa',
            field=models.CharField(blank=True, max_length=255, verbose_name='address (Dari)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address_ps',
            field=models.CharField(blank=True, max_length=255, verbose_name='address (Pashto)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='description (Dari)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_ps',
            field=models.TextField(blank=True, verbose_name='description (Pashto)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_fa',
            field=models.TextField(blank=True, verbose_name='mission (Dari)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_ps',
            field=models.TextField(blank=True, verbose_name='mission (Pashto)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_fa',
            field=models.CharField(blank=True, max_length=150, verbose_name='name (Dari)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name_ps',
            field=models.CharField(blank=True, max_length=150, verbose_name='name (Pashto)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tagline_fa',
            field=models.CharField(blank=True, max_length=255, verbose_name='tagline (Dari)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tagline_ps',
            field=models.CharField(blank=True, max_length=255, verbose_name='tagline (Pashto)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_fa',
            field=models.TextField(blank=True, verbose_name='vision (Dari)'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_ps',
            field=models.TextField(blank=True, verbose_name='vision (Pashto)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='text_fa',
            field=models.CharField(blank=True, max_length=255, verbose_name='text (Dari)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='text_ps',
            field=models.CharField(blank=True, max_length=255, verbose_name='text (Pashto)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_fa',
            field=models.CharField(blank=True, max_length=120, verbose_name='title (Dari)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_ps',
            field=models.CharField(blank=True, max_length=120, verbose_name='title (Pashto)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_text_fa',
            field=models.CharField(blank=True, max_length=60, verbose_name='cta text (Dari)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta_text_ps',
            field=models.CharField(blank=True, max_length=60, verbose_name='cta text (Pashto)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_fa',
            field=models.CharField(blank=True, max_length=255, verbose_name='subtitle (Dari)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='subtitle_ps',
            field=models.CharField(blank=True, max_length=255, verbose_name='subtitle (Pashto)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='title (Dari)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_ps',
            field=models.CharField(blank=True, max_length=200, verbose_name='title (Pashto)'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='label_fa',
            field=models.CharField(blank=True, max_length=120, verbose_name='label (Dari)'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='label_ps',
            field=models.CharField(blank=True, max_length=120, verbose_name='label (Pashto)'),
        ),
    ]
