# Generated by Django 6.1.1 on 2026-09-11 08:48

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[apps.core.validators.validate_file_size]),
        ),
    ]
