# Generated by Django 6.0.5 on 2026-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='name_fa',
            field=models.CharField(blank=True, max_length=120, verbose_name='name (Dari)'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_ps',
            field=models.CharField(blank=True, max_length=120, verbose_name='name (Pashto)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='description (Dari)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='description_ps',
            field=models.TextField(blank=True, verbose_name='description (Pashto)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='title_fa',
            field=models.CharField(blank=True, max_length=150, verbose_name='title (Dari)'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='title_ps',
            field=models.CharField(blank=True, max_length=150, verbose_name='title (Pashto)'),
        ),
    ]
