# Generated by Django 6.0.5 on 2026-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='description (Dari)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='description_ps',
            field=models.TextField(blank=True, verbose_name='description (Pashto)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location_fa',
            field=models.CharField(blank=True, max_length=120, verbose_name='location (Dari)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location_ps',
            field=models.CharField(blank=True, max_length=120, verbose_name='location (Pashto)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirements_fa',
            field=models.TextField(blank=True, verbose_name='requirements (Dari)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirements_ps',
            field=models.TextField(blank=True, verbose_name='requirements (Pashto)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='tags_fa',
            field=models.CharField(blank=True, max_length=255, verbose_name='tags (Dari)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='tags_ps',
            field=models.CharField(blank=True, max_length=255, verbose_name='tags (Pashto)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='title_fa',
            field=models.CharField(blank=True, max_length=150, verbose_name='title (Dari)'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='title_ps',
            field=models.CharField(blank=True, max_length=150, verbose_name='title (Pashto)'),
        ),
    ]
