# Generated by Django 6.0.5 on 2026-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='description (Dari)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ps',
            field=models.TextField(blank=True, verbose_name='description (Pashto)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(blank=True, max_length=120, verbose_name='name (Dari)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ps',
            field=models.CharField(blank=True, max_length=120, verbose_name='name (Pashto)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='description (Dari)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ps',
            field=models.TextField(blank=True, verbose_name='description (Pashto)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fa',
            field=models.CharField(blank=True, max_length=150, verbose_name='name (Dari)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ps',
            field=models.CharField(blank=True, max_length=150, verbose_name='name (Pashto)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_fa',
            field=models.CharField(blank=True, max_length=255, verbose_name='short description (Dari)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ps',
            field=models.CharField(blank=True, max_length=255, verbose_name='short description (Pashto)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag1_fa',
            field=models.CharField(blank=True, max_length=40, verbose_name='tag 1 (Dari)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag1_ps',
            field=models.CharField(blank=True, max_length=40, verbose_name='tag 1 (Pashto)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag2_fa',
            field=models.CharField(blank=True, max_length=40, verbose_name='tag 2 (Dari)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag2_ps',
            field=models.CharField(blank=True, max_length=40, verbose_name='tag 2 (Pashto)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text_fa',
            field=models.CharField(blank=True, max_length=150, verbose_name='alt text (Dari)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text_ps',
            field=models.CharField(blank=True, max_length=150, verbose_name='alt text (Pashto)'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='key_fa',
            field=models.CharField(blank=True, max_length=80, verbose_name='key (Dari)'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='key_ps',
            field=models.CharField(blank=True, max_length=80, verbose_name='key (Pashto)'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='value_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='value (Dari)'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='value_ps',
            field=models.CharField(blank=True, max_length=200, verbose_name='value (Pashto)'),
        ),
    ]
